# Site settings
title: Hai Blog
SEOTitle: 王海的博客 | Hai Blog
header-img: ./img/home_background.jpg
email: wanghai_huaxi@stu.scu.edu.cn
description: "这里是 @Hai 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "王海, Hai, 纳川, 王海的博客, Hai Blog, 博客, 个人网站, Life science"
url: "https://wangnachuanhai.github.io/"
baseurl: ""

# SNS settings
RSS: false
zhihu_username: 纳川
github_username: wangnachuanhai
twitter_username: wangnachuanhai

# Disqus 评论系统 (确保此项存在)
disqus_username: wangnachuanhai

# Netease settings
netease_comment: false

# Build settings
future: true
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "README.zh.md"]
anchorjs: true
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sidebar settings
sidebar: true
sidebar-about-description: "成为一名探究人类智慧的科学家"
sidebar-avatar: /img/avatar-wh.jpg

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax
page-mathjax: false

# Friends
friends: [
  { title: "乱序（Midare）", href: "http://mida.re/" },
  { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
  { title: "Kun Qian", href: "http://kunq.me" },
  { title: "Sherry Woo", href: "https://sherrywoo.me/" },
  { title: "SmdCn", href: "http://blog.smdcn.net" },
  { title: "JiyinYiyong", href: "http://tiye.me/" },
  { title: "DHong Say", href: "http://dhong.co" },
  { title: "尹峰以为", href: "http://ingf.github.io/" }
]